#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    positive=0
    negative=0
    zeros=0
    n=len(arr)
    for i in range(n):
        if arr[i]>0:
            positive+=1
        elif arr[i]<0:
            negative+=1
        elif arr[i]==0:
            zeros+=1
    perpos=positive/n
    perneg=negative/n
    perzer=zeros/n   
    print(f"{perpos:.6f}")
    print(f"{perneg:.6f}")
    print(f"{perzer:.6f}")



if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
